
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ru' | 'zh' | 'de' | 'fr' | 'es' | 'pt' | 'ar' | 'hi' | 'ms' | 'ta' | 'tl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language') as Language;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('preferred-language', lang);
  };

  const t = (key: string): string => {
    return getTranslation(key, language);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'} dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation function
const getTranslation = (key: string, language: Language): string => {
  const translations = getTranslations();
  return translations[language]?.[key] || translations['en'][key] || key;
};

// Import translations
const getTranslations = () => {
  return {
    en: {
      // Header
      'nav.community': 'Community',
      'nav.getStarted': 'Get Started',
      'nav.contribute': 'Contribute',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Pathfinders',
      'nav.joinCommunity': 'Join Community',
      
      // Hero
      'hero.welcome': 'Welcome to the',
      'hero.zorkNetwork': 'Zork Network',
      'hero.description': 'A revolutionary proof-of-work blockchain powered by the innovative kHeavyHash algorithm, derived from proven Litecoin technology. Join our diverse community of builders, creators, and visionaries shaping the future of secure, private, decentralized technology.',
      'hero.getStarted': 'Get Started',
      'hero.learnZorkcoin': 'Learn About Zorkcoin',
      'hero.provenTech': 'Proven Technology',
      'hero.provenTechDesc': 'Forked from Litecoin source code with decades of battle-tested security',
      'hero.enhancedPrivacy': 'Enhanced Privacy',
      'hero.enhancedPrivacyDesc': 'Features MWEB (MimbleWimble Extension Block) for enhanced transaction privacy',
      'hero.inclusiveCommunity': 'Inclusive Community',
      'hero.inclusiveCommunityDesc': 'Welcoming developers, artists, marketers, and blockchain newcomers',
      'hero.kHeavyHash': 'kHeavyHash Algorithm',
      'hero.kHeavyHashDesc': 'Innovative mining algorithm ensuring fair distribution and energy efficiency',
      'hero.devNotice': 'This site, like everything else for Zork Network, is still under heavy development - not everything is working yet.',
      
      // Community Roles
      'community.title': 'Find Your Place in the',
      'community.subtitle': 'Community',
      'community.description': 'Whether you\'re a seasoned blockchain developer or completely new to Web3, there\'s a meaningful way for you to contribute to the Zork Network ecosystem built on proven, secure technology.',
      'community.developers': 'Developers & Programmers',
      'community.developersDesc': 'Build smart contracts, dApps, and core protocol improvements on our Litecoin-evolved foundation',
      'community.artists': 'Artists & Creators',
      'community.artistsDesc': 'Design NFTs, create content, and build the visual identity of our secure ecosystem',
      'community.marketers': 'Marketers & Influencers',
      'community.marketersDesc': 'Spread awareness about our privacy-focused blockchain and grow our community reach',
      'community.business': 'Business Developers',
      'community.businessDesc': 'Form partnerships, identify opportunities, and drive adoption of Zorkcoin',
      'community.leaders': 'Community Leaders',
      'community.leadersDesc': 'Moderate discussions, organize events, and welcome newcomers to our proven technology',
      'community.enthusiasts': 'Web3 Enthusiasts',
      'community.enthusiastsDesc': 'Test features, provide feedback, and help onboard new users to our secure network',
      
      // Getting Started
      'gettingStarted.title': 'Choose Your',
      'gettingStarted.subtitle': 'Journey',
      'gettingStarted.description': 'Multiple pathways designed for different experience levels and interests. Pick the one that best matches where you are and where you want to go on our secure, proven platform.',
      'gettingStarted.beginner': 'Complete Beginner',
      'gettingStarted.beginnerDesc': 'New to blockchain and crypto? Start here!',
      'gettingStarted.technical': 'Technical User',
      'gettingStarted.technicalDesc': 'Ready to dive into our proven technology?',
      'gettingStarted.contributor': 'Community Contributor',
      'gettingStarted.contributorDesc': 'Want to help grow our secure ecosystem?',
      'gettingStarted.advocate': 'Privacy Advocate',
      'gettingStarted.advocateDesc': 'Building secure, private solutions on Zork?',
      'gettingStarted.startLearning': 'Start Learning',
      'gettingStarted.getTechnical': 'Get Technical',
      'gettingStarted.getInvolved': 'Get Involved',
      
      // Footer
      'footer.description': 'Building the future of secure, private decentralized technology with proven Litecoin-derived foundations and the innovative kHeavyHash algorithm.',
      'footer.community': 'Community',
      'footer.developers': 'Developers',
      'footer.resources': 'Resources',
      'footer.documentation': 'Documentation',
      'footer.apiReference': 'API Reference',
      'footer.whitepaper': 'Whitepaper',
      'footer.roadmap': 'Roadmap',
      'footer.support': 'Support',
      'footer.privacyPolicy': 'Privacy Policy',
      'footer.terms': 'Terms of Service',
      'footer.cookies': 'Cookie Policy',
      'footer.copyright': '© 2025 Zork Network. All rights reserved.',
      'footer.pathfinders': 'Pathfinders Program',
      
      // Language Selector
      'language.select': 'Select Language',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    ru: {
      // Header
      'nav.community': 'Сообщество',
      'nav.getStarted': 'Начать',
      'nav.contribute': 'Участвовать',
      'nav.zorkcoin': 'Зорккоин',
      'nav.pathfinders': 'Первопроходцы',
      'nav.joinCommunity': 'Присоединиться',
      
      // Hero
      'hero.welcome': 'Добро пожаловать в',
      'hero.zorkNetwork': 'Сеть Zork',
      'hero.description': 'Революционный блокчейн с алгоритмом доказательства работы kHeavyHash, основанный на проверенной технологии Litecoin. Присоединяйтесь к нашему разнообразному сообществу разработчиков, создателей и визионеров, формирующих будущее безопасной, приватной, децентрализованной технологии.',
      'hero.getStarted': 'Начать',
      'hero.learnZorkcoin': 'Узнать о Зорккоин',
      'hero.provenTech': 'Проверенная Технология',
      'hero.provenTechDesc': 'Форк исходного кода Litecoin с десятилетиями проверенной безопасности',
      'hero.enhancedPrivacy': 'Усиленная Приватность',
      'hero.enhancedPrivacyDesc': 'Функции MWEB (MimbleWimble Extension Block) для усиленной приватности транзакций',
      'hero.inclusiveCommunity': 'Инклюзивное Сообщество',
      'hero.inclusiveCommunityDesc': 'Приветствуем разработчиков, художников, маркетологов и новичков в блокчейне',
      'hero.kHeavyHash': 'Алгоритм kHeavyHash',
      'hero.kHeavyHashDesc': 'Инновационный алгоритм майнинга, обеспечивающий справедливое распределение и энергоэффективность',
      'hero.devNotice': 'Этот сайт, как и все остальное для Zork Network, все еще находится в стадии активной разработки - не все пока работает.',
      
      // Community Roles
      'community.title': 'Найдите свое место в',
      'community.subtitle': 'Сообществе',
      'community.description': 'Независимо от того, являетесь ли вы опытным разработчиком блокчейна или совершенно новичком в Web3, есть значимый способ внести свой вклад в экосистему Zork Network, построенную на проверенной, безопасной технологии.',
      'community.developers': 'Разработчики и Программисты',
      'community.developersDesc': 'Создавайте смарт-контракты, dApps и улучшения основного протокола на нашей основе, развившейся из Litecoin',
      'community.artists': 'Художники и Творцы',
      'community.artistsDesc': 'Создавайте NFT, контент и визуальную идентичность нашей безопасной экосистемы',
      'community.marketers': 'Маркетологи и Инфлюенсеры',
      'community.marketersDesc': 'Распространяйте информацию о нашем блокчейне, ориентированном на приватность, и развивайте наше сообщество',
      'community.business': 'Бизнес-разработчики',
      'community.businessDesc': 'Формируйте партнерства, выявляйте возможности и способствуйте принятию Зорккоин',
      'community.leaders': 'Лидеры Сообщества',
      'community.leadersDesc': 'Модерируйте дискуссии, организуйте мероприятия и приветствуйте новичков в нашей проверенной технологии',
      'community.enthusiasts': 'Энтузиасты Web3',
      'community.enthusiastsDesc': 'Тестируйте функции, предоставляйте отзывы и помогайте новым пользователям присоединиться к нашей безопасной сети',
      
      // Getting Started
      'gettingStarted.title': 'Выберите свой',
      'gettingStarted.subtitle': 'Путь',
      'gettingStarted.description': 'Множественные пути, разработанные для разных уровней опыта и интересов. Выберите тот, который лучше всего соответствует тому, где вы находитесь и куда хотите идти на нашей безопасной, проверенной платформе.',
      'gettingStarted.beginner': 'Полный Новичок',
      'gettingStarted.beginnerDesc': 'Новичок в блокчейне и крипто? Начните здесь!',
      'gettingStarted.technical': 'Технический Пользователь',
      'gettingStarted.technicalDesc': 'Готовы погрузиться в нашу проверенную технологию?',
      'gettingStarted.contributor': 'Участник Сообщества',
      'gettingStarted.contributorDesc': 'Хотите помочь развить нашу безопасную экосистему?',
      'gettingStarted.advocate': 'Защитник Приватности',
      'gettingStarted.advocateDesc': 'Создаете безопасные, приватные решения на Zork?',
      'gettingStarted.startLearning': 'Начать Изучение',
      'gettingStarted.getTechnical': 'Перейти к Технике',
      'gettingStarted.getInvolved': 'Участвовать',
      
      // Footer
      'footer.description': 'Строим будущее безопасной, приватной децентрализованной технологии с проверенными основами, производными от Litecoin, и инновационным алгоритмом kHeavyHash.',
      'footer.community': 'Сообщество',
      'footer.developers': 'Разработчики',
      'footer.resources': 'Ресурсы',
      'footer.documentation': 'Документация',
      'footer.apiReference': 'Справка по API',
      'footer.whitepaper': 'Техническая документация',
      'footer.roadmap': 'Дорожная карта',
      'footer.support': 'Поддержка',
      'footer.privacyPolicy': 'Политика конфиденциальности',
      'footer.terms': 'Условия обслуживания',
      'footer.cookies': 'Политика куки',
      'footer.copyright': '© 2025 Zork Network. Все права защищены.',
      'footer.pathfinders': 'Программа Первопроходцев',
      
      // Language Selector
      'language.select': 'Выбрать язык',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    zh: {
      // Header
      'nav.community': '社区',
      'nav.getStarted': '开始',
      'nav.contribute': '贡献',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': '探路者',
      'nav.joinCommunity': '加入社区',
      
      // Hero
      'hero.welcome': '欢迎来到',
      'hero.zorkNetwork': 'Zork网络',
      'hero.description': '由创新的kHeavyHash算法驱动的革命性工作量证明区块链，源于经过验证的莱特币技术。加入我们多元化的建设者、创作者和远见者社区，共同塑造安全、私密、去中心化技术的未来。',
      'hero.getStarted': '开始',
      'hero.learnZorkcoin': '了解Zorkcoin',
      'hero.provenTech': '经过验证的技术',
      'hero.provenTechDesc': '分叉自莱特币源代码，拥有数十年经过实战检验的安全性',
      'hero.enhancedPrivacy': '增强隐私',
      'hero.enhancedPrivacyDesc': '具有MWEB（MimbleWimble扩展块）功能，增强交易隐私',
      'hero.inclusiveCommunity': '包容性社区',
      'hero.inclusiveCommunityDesc': '欢迎开发者、艺术家、营销人员和区块链新手',
      'hero.kHeavyHash': 'kHeavyHash算法',
      'hero.kHeavyHashDesc': '创新的挖矿算法，确保公平分配和能源效率',
      'hero.devNotice': '这个网站，就像Zork网络的其他一切一样，仍在大力开发中 - 不是所有功能都在工作。',
      
      // Community Roles
      'community.title': '在',
      'community.subtitle': '社区中找到您的位置',
      'community.description': '无论您是经验丰富的区块链开发者还是Web3的完全新手，都有一种有意义的方式为建立在经过验证、安全技术基础上的Zork网络生态系统做出贡献。',
      'community.developers': '开发者和程序员',
      'community.developersDesc': '在我们从莱特币演化的基础上构建智能合约、dApps和核心协议改进',
      'community.artists': '艺术家和创作者',
      'community.artistsDesc': '设计NFT，创建内容，构建我们安全生态系统的视觉身份',
      'community.marketers': '营销人员和影响者',
      'community.marketersDesc': '传播我们专注隐私的区块链的信息，发展我们的社区影响力',
      'community.business': '业务开发者',
      'community.businessDesc': '建立合作伙伴关系，识别机会，推动Zorkcoin的采用',
      'community.leaders': '社区领导者',
      'community.leadersDesc': '主持讨论，组织活动，欢迎新来者加入我们经过验证的技术',
      'community.enthusiasts': 'Web3爱好者',
      'community.enthusiastsDesc': '测试功能，提供反馈，帮助新用户加入我们的安全网络',
      
      // Getting Started
      'gettingStarted.title': '选择您的',
      'gettingStarted.subtitle': '旅程',
      'gettingStarted.description': '为不同经验水平和兴趣设计的多种路径。选择最符合您现在所处位置以及在我们安全、经过验证的平台上想要前往的地方的路径。',
      'gettingStarted.beginner': '完全新手',
      'gettingStarted.beginnerDesc': '区块链和加密货币新手？从这里开始！',
      'gettingStarted.technical': '技术用户',
      'gettingStarted.technicalDesc': '准备深入了解我们经过验证的技术？',
      'gettingStarted.contributor': '社区贡献者',
      'gettingStarted.contributorDesc': '想要帮助发展我们的安全生态系统？',
      'gettingStarted.advocate': '隐私倡导者',
      'gettingStarted.advocateDesc': '在Zork上构建安全、私密的解决方案？',
      'gettingStarted.startLearning': '开始学习',
      'gettingStarted.getTechnical': '深入技术',
      'gettingStarted.getInvolved': '参与其中',
      
      // Footer
      'footer.description': '用经过验证的莱特币衍生基础和创新的kHeavyHash算法构建安全、私密的去中心化技术的未来。',
      'footer.community': '社区',
      'footer.developers': '开发者',
      'footer.resources': '资源',
      'footer.documentation': '文档',
      'footer.apiReference': 'API参考',
      'footer.whitepaper': '白皮书',
      'footer.roadmap': '路线图',
      'footer.support': '支持',
      'footer.privacyPolicy': '隐私政策',
      'footer.terms': '服务条款',
      'footer.cookies': 'Cookie政策',
      'footer.copyright': '© 2025 Zork网络。保留所有权利。',
      'footer.pathfinders': '探路者计划',
      
      // Language Selector
      'language.select': '选择语言',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    de: {
      // Header
      'nav.community': 'Gemeinschaft',
      'nav.getStarted': 'Loslegen',
      'nav.contribute': 'Beitragen',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Pfadfinder',
      'nav.joinCommunity': 'Beitreten',
      
      // Hero
      'hero.welcome': 'Willkommen im',
      'hero.zorkNetwork': 'Zork Netzwerk',
      'hero.description': 'Eine revolutionäre Proof-of-Work-Blockchain, angetrieben vom innovativen kHeavyHash-Algorithmus, basierend auf bewährter Litecoin-Technologie. Treten Sie unserer vielfältigen Gemeinschaft von Entwicklern, Schöpfern und Visionären bei, die die Zukunft sicherer, privater, dezentraler Technologie gestalten.',
      'hero.getStarted': 'Loslegen',
      'hero.learnZorkcoin': 'Über Zorkcoin lernen',
      'hero.provenTech': 'Bewährte Technologie',
      'hero.provenTechDesc': 'Abgezweigt vom Litecoin-Quellcode mit jahrzehntelang kampferprobter Sicherheit',
      'hero.enhancedPrivacy': 'Erweiterte Privatsphäre',
      'hero.enhancedPrivacyDesc': 'Enthält MWEB (MimbleWimble Extension Block) für erweiterte Transaktionsprivatsphäre',
      'hero.inclusiveCommunity': 'Inklusive Gemeinschaft',
      'hero.inclusiveCommunityDesc': 'Begrüßt Entwickler, Künstler, Vermarkter und Blockchain-Neulinge',
      'hero.kHeavyHash': 'kHeavyHash-Algorithmus',
      'hero.kHeavyHashDesc': 'Innovativer Mining-Algorithmus, der faire Verteilung und Energieeffizienz gewährleistet',
      'hero.devNotice': 'Diese Website, wie alles andere für das Zork-Netzwerk, befindet sich noch in intensiver Entwicklung - nicht alles funktioniert noch.',
      
      // Community Roles
      'community.title': 'Finden Sie Ihren Platz in der',
      'community.subtitle': 'Gemeinschaft',
      'community.description': 'Ob Sie ein erfahrener Blockchain-Entwickler oder völlig neu in Web3 sind, es gibt einen sinnvollen Weg für Sie, zum Zork Network-Ökosystem beizutragen, das auf bewährter, sicherer Technologie aufbaut.',
      'community.developers': 'Entwickler & Programmierer',
      'community.developersDesc': 'Entwickeln Sie Smart Contracts, dApps und Kernprotokoll-Verbesserungen auf unserer von Litecoin weiterentwickelten Grundlage',
      'community.artists': 'Künstler & Schöpfer',
      'community.artistsDesc': 'Gestalten Sie NFTs, erstellen Sie Inhalte und bauen Sie die visuelle Identität unseres sicheren Ökosystems auf',
      'community.marketers': 'Vermarkter & Influencer',
      'community.marketersDesc': 'Verbreiten Sie das Bewusstsein für unsere privatsphäre-fokussierte Blockchain und erweitern Sie unsere Gemeinschaftsreichweite',
      'community.business': 'Geschäftsentwickler',
      'community.businessDesc': 'Bilden Sie Partnerschaften, identifizieren Sie Möglichkeiten und fördern Sie die Adoption von Zorkcoin',
      'community.leaders': 'Gemeinschaftsführer',
      'community.leadersDesc': 'Moderieren Sie Diskussionen, organisieren Sie Veranstaltungen und begrüßen Sie Neuankömmlinge in unserer bewährten Technologie',
      'community.enthusiasts': 'Web3-Enthusiasten',
      'community.enthusiastsDesc': 'Testen Sie Funktionen, geben Sie Feedback und helfen Sie neuen Benutzern beim Einstieg in unser sicheres Netzwerk',
      
      // Getting Started
      'gettingStarted.title': 'Wählen Sie Ihre',
      'gettingStarted.subtitle': 'Reise',
      'gettingStarted.description': 'Mehrere Wege, die für verschiedene Erfahrungsniveaus und Interessen entwickelt wurden. Wählen Sie denjenigen, der am besten zu Ihrem aktuellen Stand und Ihren Zielen auf unserer sicheren, bewährten Plattform passt.',
      'gettingStarted.beginner': 'Kompletter Anfänger',
      'gettingStarted.beginnerDesc': 'Neu bei Blockchain und Krypto? Starten Sie hier!',
      'gettingStarted.technical': 'Technischer Benutzer',
      'gettingStarted.technicalDesc': 'Bereit, in unsere bewährte Technologie einzutauchen?',
      'gettingStarted.contributor': 'Gemeinschaftsbeitragender',
      'gettingStarted.contributorDesc': 'Möchten Sie beim Wachstum unseres sicheren Ökosystems helfen?',
      'gettingStarted.advocate': 'Privatsphäre-Befürworter',
      'gettingStarted.advocateDesc': 'Entwickeln Sie sichere, private Lösungen auf Zork?',
      'gettingStarted.startLearning': 'Lernen beginnen',
      'gettingStarted.getTechnical': 'Technisch werden',
      'gettingStarted.getInvolved': 'Mitmachen',
      
      // Footer
      'footer.description': 'Aufbau der Zukunft sicherer, privater dezentraler Technologie mit bewährten Litecoin-abgeleiteten Grundlagen und dem innovativen kHeavyHash-Algorithmus.',
      'footer.community': 'Gemeinschaft',
      'footer.developers': 'Entwickler',
      'footer.resources': 'Ressourcen',
      'footer.documentation': 'Dokumentation',
      'footer.apiReference': 'API-Referenz',
      'footer.whitepaper': 'Whitepaper',
      'footer.roadmap': 'Roadmap',
      'footer.support': 'Support',
      'footer.privacyPolicy': 'Datenschutzrichtlinie',
      'footer.terms': 'Nutzungsbedingungen',
      'footer.cookies': 'Cookie-Richtlinie',
      'footer.copyright': '© 2025 Zork Network. Alle Rechte vorbehalten.',
      'footer.pathfinders': 'Pfadfinder-Programm',
      
      // Language Selector
      'language.select': 'Sprache auswählen',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    fr: {
      // Header
      'nav.community': 'Communauté',
      'nav.getStarted': 'Commencer',
      'nav.contribute': 'Contribuer',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Éclaireurs',
      'nav.joinCommunity': 'Rejoindre',
      
      // Hero
      'hero.welcome': 'Bienvenue dans le',
      'hero.zorkNetwork': 'Réseau Zork',
      'hero.description': 'Une blockchain révolutionnaire de preuve de travail alimentée par l\'algorithme innovant kHeavyHash, dérivé de la technologie Litecoin éprouvée. Rejoignez notre communauté diversifiée de constructeurs, créateurs et visionnaires façonnant l\'avenir de la technologie décentralisée sécurisée et privée.',
      'hero.getStarted': 'Commencer',
      'hero.learnZorkcoin': 'Apprendre Zorkcoin',
      'hero.provenTech': 'Technologie Éprouvée',
      'hero.provenTechDesc': 'Dérivé du code source Litecoin avec des décennies de sécurité éprouvée au combat',
      'hero.enhancedPrivacy': 'Confidentialité Renforcée',
      'hero.enhancedPrivacyDesc': 'Comprend MWEB (MimbleWimble Extension Block) pour une confidentialité de transaction renforcée',
      'hero.inclusiveCommunity': 'Communauté Inclusive',
      'hero.inclusiveCommunityDesc': 'Accueille les développeurs, artistes, marketeurs et nouveaux arrivants blockchain',
      'hero.kHeavyHash': 'Algorithme kHeavyHash',
      'hero.kHeavyHashDesc': 'Algorithme de minage innovant assurant une distribution équitable et l\'efficacité énergétique',
      'hero.devNotice': 'Ce site, comme tout le reste pour le réseau Zork, est encore en développement intensif - tout ne fonctionne pas encore.',
      
      // Community Roles
      'community.title': 'Trouvez votre place dans la',
      'community.subtitle': 'Communauté',
      'community.description': 'Que vous soyez un développeur blockchain expérimenté ou complètement nouveau dans Web3, il y a un moyen significatif pour vous de contribuer à l\'écosystème Zork Network construit sur une technologie éprouvée et sécurisée.',
      'community.developers': 'Développeurs & Programmeurs',
      'community.developersDesc': 'Construisez des contrats intelligents, dApps et améliorations du protocole central sur notre fondation évoluée de Litecoin',
      'community.artists': 'Artistes & Créateurs',
      'community.artistsDesc': 'Concevez des NFT, créez du contenu et construisez l\'identité visuelle de notre écosystème sécurisé',
      'community.marketers': 'Marketeurs & Influenceurs',
      'community.marketersDesc': 'Sensibilisez à notre blockchain axée sur la confidentialité et développez la portée de notre communauté',
      'community.business': 'Développeurs d\'Affaires',
      'community.businessDesc': 'Formez des partenariats, identifiez des opportunités et favorisez l\'adoption de Zorkcoin',
      'community.leaders': 'Leaders Communautaires',
      'community.leadersDesc': 'Modérez les discussions, organisez des événements et accueillez les nouveaux arrivants dans notre technologie éprouvée',
      'community.enthusiasts': 'Enthousiastes Web3',
      'community.enthusiastsDesc': 'Testez les fonctionnalités, fournissez des commentaires et aidez les nouveaux utilisateurs à rejoindre notre réseau sécurisé',
      
      // Getting Started
      'gettingStarted.title': 'Choisissez votre',
      'gettingStarted.subtitle': 'Parcours',
      'gettingStarted.description': 'Plusieurs parcours conçus pour différents niveaux d\'expérience et intérêts. Choisissez celui qui correspond le mieux à où vous êtes et où vous voulez aller sur notre plateforme sécurisée et éprouvée.',
      'gettingStarted.beginner': 'Débutant Complet',
      'gettingStarted.beginnerDesc': 'Nouveau dans la blockchain et la crypto ? Commencez ici !',
      'gettingStarted.technical': 'Utilisateur Technique',
      'gettingStarted.technicalDesc': 'Prêt à plonger dans notre technologie éprouvée ?',
      'gettingStarted.contributor': 'Contributeur Communautaire',
      'gettingStarted.contributorDesc': 'Vous voulez aider à développer notre écosystème sécurisé ?',
      'gettingStarted.advocate': 'Défenseur de la Confidentialité',
      'gettingStarted.advocateDesc': 'Construire des solutions sécurisées et privées sur Zork ?',
      'gettingStarted.startLearning': 'Commencer l\'Apprentissage',
      'gettingStarted.getTechnical': 'Devenir Technique',
      'gettingStarted.getInvolved': 'S\'Impliquer',
      
      // Footer
      'footer.description': 'Construire l\'avenir de la technologie décentralisée sécurisée et privée avec des fondations éprouvées dérivées de Litecoin et l\'algorithme innovant kHeavyHash.',
      'footer.community': 'Communauté',
      'footer.developers': 'Développeurs',
      'footer.resources': 'Ressources',
      'footer.documentation': 'Documentation',
      'footer.apiReference': 'Référence API',
      'footer.whitepaper': 'Livre Blanc',
      'footer.roadmap': 'Feuille de Route',
      'footer.support': 'Support',
      'footer.privacyPolicy': 'Politique de Confidentialité',
      'footer.terms': 'Conditions de Service',
      'footer.cookies': 'Politique des Cookies',
      'footer.copyright': '© 2025 Zork Network. Tous droits réservés.',
      'footer.pathfinders': 'Programme Éclaireurs',
      
      // Language Selector
      'language.select': 'Sélectionner la langue',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    es: {
      // Header
      'nav.community': 'Comunidad',
      'nav.getStarted': 'Comenzar',
      'nav.contribute': 'Contribuir',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Exploradores',
      'nav.joinCommunity': 'Unirse',
      
      // Hero
      'hero.welcome': 'Bienvenido a la',
      'hero.zorkNetwork': 'Red Zork',
      'hero.description': 'Una blockchain revolucionaria de prueba de trabajo impulsada por el innovador algoritmo kHeavyHash, derivado de la tecnología probada de Litecoin. Únete a nuestra diversa comunidad de constructores, creadores y visionarios que dan forma al futuro de la tecnología descentralizada segura y privada.',
      'hero.getStarted': 'Comenzar',
      'hero.learnZorkcoin': 'Aprender sobre Zorkcoin',
      'hero.provenTech': 'Tecnología Probada',
      'hero.provenTechDesc': 'Derivado del código fuente de Litecoin con décadas de seguridad probada en batalla',
      'hero.enhancedPrivacy': 'Privacidad Mejorada',
      'hero.enhancedPrivacyDesc': 'Incluye MWEB (MimbleWimble Extension Block) para privacidad de transacciones mejorada',
      'hero.inclusiveCommunity': 'Comunidad Inclusiva',
      'hero.inclusiveCommunityDesc': 'Da la bienvenida a desarrolladores, artistas, mercadólogos y recién llegados a blockchain',
      'hero.kHeavyHash': 'Algoritmo kHeavyHash',
      'hero.kHeavyHashDesc': 'Algoritmo de minería innovador que garantiza distribución justa y eficiencia energética',
      'hero.devNotice': 'Este sitio, como todo lo demás para la Red Zork, todavía está en desarrollo intensivo - no todo está funcionando aún.',
      
      // Community Roles
      'community.title': 'Encuentra tu lugar en la',
      'community.subtitle': 'Comunidad',
      'community.description': 'Ya seas un desarrollador blockchain experimentado o completamente nuevo en Web3, hay una manera significativa para que contribuyas al ecosistema de Zork Network construido sobre tecnología probada y segura.',
      'community.developers': 'Desarrolladores y Programadores',
      'community.developersDesc': 'Construye contratos inteligentes, dApps y mejoras del protocolo central en nuestra base evolucionada de Litecoin',
      'community.artists': 'Artistas y Creadores',
      'community.artistsDesc': 'Diseña NFTs, crea contenido y construye la identidad visual de nuestro ecosistema seguro',
      'community.marketers': 'Mercadólogos e Influencers',
      'community.marketersDesc': 'Difunde la conciencia sobre nuestra blockchain enfocada en privacidad y haz crecer el alcance de nuestra comunidad',
      'community.business': 'Desarrolladores de Negocios',
      'community.businessDesc': 'Forma asociaciones, identifica oportunidades e impulsa la adopción de Zorkcoin',
      'community.leaders': 'Líderes Comunitarios',
      'community.leadersDesc': 'Modera discusiones, organiza eventos y da la bienvenida a los recién llegados a nuestra tecnología probada',
      'community.enthusiasts': 'Entusiastas Web3',
      'community.enthusiastsDesc': 'Prueba características, proporciona retroalimentación y ayuda a nuevos usuarios a unirse a nuestra red segura',
      
      // Getting Started
      'gettingStarted.title': 'Elige tu',
      'gettingStarted.subtitle': 'Viaje',
      'gettingStarted.description': 'Múltiples caminos diseñados para diferentes niveles de experiencia e intereses. Elige el que mejor coincida con donde estás y donde quieres ir en nuestra plataforma segura y probada.',
      'gettingStarted.beginner': 'Principiante Completo',
      'gettingStarted.beginnerDesc': '¿Nuevo en blockchain y cripto? ¡Comienza aquí!',
      'gettingStarted.technical': 'Usuario Técnico',
      'gettingStarted.technicalDesc': '¿Listo para sumergirte en nuestra tecnología probada?',
      'gettingStarted.contributor': 'Contribuidor Comunitario',
      'gettingStarted.contributorDesc': '¿Quieres ayudar a hacer crecer nuestro ecosistema seguro?',
      'gettingStarted.advocate': 'Defensor de la Privacidad',
      'gettingStarted.advocateDesc': '¿Construyendo soluciones seguras y privadas en Zork?',
      'gettingStarted.startLearning': 'Comenzar a Aprender',
      'gettingStarted.getTechnical': 'Volverse Técnico',
      'gettingStarted.getInvolved': 'Involucrarse',
      
      // Footer
      'footer.description': 'Construyendo el futuro de la tecnología descentralizada segura y privada con fundaciones probadas derivadas de Litecoin y el innovador algoritmo kHeavyHash.',
      'footer.community': 'Comunidad',
      'footer.developers': 'Desarrolladores',
      'footer.resources': 'Recursos',
      'footer.documentation': 'Documentación',
      'footer.apiReference': 'Referencia API',
      'footer.whitepaper': 'Documento Técnico',
      'footer.roadmap': 'Hoja de Ruta',
      'footer.support': 'Soporte',
      'footer.privacyPolicy': 'Política de Privacidad',
      'footer.terms': 'Términos de Servicio',
      'footer.cookies': 'Política de Cookies',
      'footer.copyright': '© 2025 Red Zork. Todos los derechos reservados.',
      'footer.pathfinders': 'Programa Exploradores',
      
      // Language Selector
      'language.select': 'Seleccionar idioma',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    pt: {
      // Header
      'nav.community': 'Comunidade',
      'nav.getStarted': 'Começar',
      'nav.contribute': 'Contribuir',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Desbravadores',
      'nav.joinCommunity': 'Participar',
      
      // Hero
      'hero.welcome': 'Bem-vindo à',
      'hero.zorkNetwork': 'Rede Zork',
      'hero.description': 'Uma blockchain revolucionária de prova de trabalho alimentada pelo inovador algoritmo kHeavyHash, derivado da tecnologia comprovada do Litecoin. Junte-se à nossa comunidade diversificada de construtores, criadores e visionários moldando o futuro da tecnologia descentralizada segura e privada.',
      'hero.getStarted': 'Começar',
      'hero.learnZorkcoin': 'Aprender sobre Zorkcoin',
      'hero.provenTech': 'Tecnologia Comprovada',
      'hero.provenTechDesc': 'Derivado do código fonte do Litecoin com décadas de segurança testada em batalha',
      'hero.enhancedPrivacy': 'Privacidade Aprimorada',
      'hero.enhancedPrivacyDesc': 'Apresenta MWEB (MimbleWimble Extension Block) para privacidade de transação aprimorada',
      'hero.inclusiveCommunity': 'Comunidade Inclusiva',
      'hero.inclusiveCommunityDesc': 'Recebe desenvolvedores, artistas, profissionais de marketing e novatos em blockchain',
      'hero.kHeavyHash': 'Algoritmo kHeavyHash',
      'hero.kHeavyHashDesc': 'Algoritmo de mineração inovador garantindo distribuição justa e eficiência energética',
      'hero.devNotice': 'Este site, como tudo o mais para a Rede Zork, ainda está em desenvolvimento intensivo - nem tudo está funcionando ainda.',
      
      // Community Roles
      'community.title': 'Encontre seu lugar na',
      'community.subtitle': 'Comunidade',
      'community.description': 'Seja você um desenvolvedor blockchain experiente ou completamente novo no Web3, há uma maneira significativa para você contribuir com o ecossistema Zork Network construído sobre tecnologia comprovada e segura.',
      'community.developers': 'Desenvolvedores e Programadores',
      'community.developersDesc': 'Construa contratos inteligentes, dApps e melhorias do protocolo central em nossa base evoluída do Litecoin',
      'community.artists': 'Artistas e Criadores',
      'community.artistsDesc': 'Projete NFTs, crie conteúdo e construa a identidade visual do nosso ecossistema seguro',
      'community.marketers': 'Profissionais de Marketing e Influenciadores',
      'community.marketersDesc': 'Espalhe a consciência sobre nossa blockchain focada em privacidade e cresça o alcance da nossa comunidade',
      'community.business': 'Desenvolvedores de Negócios',
      'community.businessDesc': 'Forme parcerias, identifique oportunidades e impulsione a adoção do Zorkcoin',
      'community.leaders': 'Líderes Comunitários',
      'community.leadersDesc': 'Modere discussões, organize eventos e receba novatos em nossa tecnologia comprovada',
      'community.enthusiasts': 'Entusiastas Web3',
      'community.enthusiastsDesc': 'Teste recursos, forneça feedback e ajude novos usuários a se juntarem à nossa rede segura',
      
      // Getting Started
      'gettingStarted.title': 'Escolha sua',
      'gettingStarted.subtitle': 'Jornada',
      'gettingStarted.description': 'Múltiplos caminhos projetados para diferentes níveis de experiência e interesses. Escolha aquele que melhor combina com onde você está e onde quer chegar em nossa plataforma segura e comprovada.',
      'gettingStarted.beginner': 'Iniciante Completo',
      'gettingStarted.beginnerDesc': 'Novo em blockchain e cripto? Comece aqui!',
      'gettingStarted.technical': 'Usuário Técnico',
      'gettingStarted.technicalDesc': 'Pronto para mergulhar em nossa tecnologia comprovada?',
      'gettingStarted.contributor': 'Contribuidor Comunitário',
      'gettingStarted.contributorDesc': 'Quer ajudar a crescer nosso ecossistema seguro?',
      'gettingStarted.advocate': 'Defensor da Privacidade',
      'gettingStarted.advocateDesc': 'Construindo soluções seguras e privadas no Zork?',
      'gettingStarted.startLearning': 'Começar a Aprender',
      'gettingStarted.getTechnical': 'Ficar Técnico',
      'gettingStarted.getInvolved': 'Se Envolver',
      
      // Footer
      'footer.description': 'Construindo o futuro da tecnologia descentralizada segura e privada com fundações comprovadas derivadas do Litecoin e o inovador algoritmo kHeavyHash.',
      'footer.community': 'Comunidade',
      'footer.developers': 'Desenvolvedores',
      'footer.resources': 'Recursos',
      'footer.documentation': 'Documentação',
      'footer.apiReference': 'Referência da API',
      'footer.whitepaper': 'Whitepaper',
      'footer.roadmap': 'Roteiro',
      'footer.support': 'Suporte',
      'footer.privacyPolicy': 'Política de Privacidade',
      'footer.terms': 'Termos de Serviço',
      'footer.cookies': 'Política de Cookies',
      'footer.copyright': '© 2025 Rede Zork. Todos os direitos reservados.',
      'footer.pathfinders': 'Programa Desbravadores',
      
      // Language Selector
      'language.select': 'Selecionar idioma',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    ar: {
      // Header
      'nav.community': 'المجتمع',
      'nav.getStarted': 'البدء',
      'nav.contribute': 'المساهمة',
      'nav.zorkcoin': 'زوركوين',
      'nav.pathfinders': 'الرواد',
      'nav.joinCommunity': 'انضم إلينا',
      
      // Hero
      'hero.welcome': 'مرحباً بك في',
      'hero.zorkNetwork': 'شبكة زورك',
      'hero.description': 'بلوك تشين ثوري لإثبات العمل مدعوم بخوارزمية kHeavyHash المبتكرة، مشتق من تكنولوجيا لايتكوين المثبتة. انضم إلى مجتمعنا المتنوع من البناة والمبدعين والرؤساء الذين يشكلون مستقبل التكنولوجيا اللامركزية الآمنة والخاصة.',
      'hero.getStarted': 'البدء',
      'hero.learnZorkcoin': 'تعلم عن زوركوين',
      'hero.provenTech': 'تكنولوجيا مثبتة',
      'hero.provenTechDesc': 'مشتق من كود لايتكوين المصدري مع عقود من الأمان المختبر في المعارك',
      'hero.enhancedPrivacy': 'خصوصية محسنة',
      'hero.enhancedPrivacyDesc': 'يتضمن MWEB (كتلة تمديد MimbleWimble) لخصوصية المعاملات المحسنة',
      'hero.inclusiveCommunity': 'مجتمع شامل',
      'hero.inclusiveCommunityDesc': 'يرحب بالمطورين والفنانين والمسوقين والوافدين الجدد إلى البلوك تشين',
      'hero.kHeavyHash': 'خوارزمية kHeavyHash',
      'hero.kHeavyHashDesc': 'خوارزمية تعدين مبتكرة تضمن التوزيع العادل والكفاءة في استخدام الطاقة',
      'hero.devNotice': 'هذا الموقع، مثل كل شيء آخر في شبكة زورك، لا يزال قيد التطوير المكثف - ليس كل شيء يعمل بعد.',
      
      // Community Roles
      'community.title': 'اعثر على مكانك في',
      'community.subtitle': 'المجتمع',
      'community.description': 'سواء كنت مطور بلوك تشين متمرس أو جديد تماماً على Web3، هناك طريقة مجدية لك للمساهمة في نظام Zork Network البيئي المبني على تكنولوجيا مثبتة وآمنة.',
      'community.developers': 'المطورون والمبرمجون',
      'community.developersDesc': 'ابني العقود الذكية و dApps وتحسينات البروتوكول الأساسي على أساسنا المتطور من لايتكوين',
      'community.artists': 'الفنانون والمبدعون',
      'community.artistsDesc': 'صمم NFTs، وأنشئ المحتوى، وابني الهوية البصرية لنظامنا البيئي الآمن',
      'community.marketers': 'المسوقون والمؤثرون',
      'community.marketersDesc': 'انشر الوعي حول بلوك تشيننا المركز على الخصوصية ونمي وصول مجتمعنا',
      'community.business': 'مطوري الأعمال',
      'community.businessDesc': 'كون شراكات، واحدد الفرص، وادفع تبني زوركوين',
      'community.leaders': 'قادة المجتمع',
      'community.leadersDesc': 'اشرف على النقاشات، ونظم الأحداث، ورحب بالوافدين الجدد إلى تكنولوجيتنا المثبتة',
      'community.enthusiasts': 'متحمسو Web3',
      'community.enthusiastsDesc': 'اختبر الميزات، وقدم التغذية الراجعة، وساعد المستخدمين الجدد على الانضمام إلى شبكتنا الآمنة',
      
      // Getting Started
      'gettingStarted.title': 'اختر',
      'gettingStarted.subtitle': 'رحلتك',
      'gettingStarted.description': 'مسارات متعددة مصممة لمستويات خبرة ومصالح مختلفة. اختر الذي يطابق بشكل أفضل أين أنت وأين تريد أن تذهب على منصتنا الآمنة والمثبتة.',
      'gettingStarted.beginner': 'مبتدئ كامل',
      'gettingStarted.beginnerDesc': 'جديد على البلوك تشين والعملات المشفرة؟ ابدأ هنا!',
      'gettingStarted.technical': 'مستخدم تقني',
      'gettingStarted.technicalDesc': 'جاهز للغوص في تكنولوجيتنا المثبتة؟',
      'gettingStarted.contributor': 'مساهم في المجتمع',
      'gettingStarted.contributorDesc': 'تريد المساعدة في نمو نظامنا البيئي الآمن؟',
      'gettingStarted.advocate': 'مدافع عن الخصوصية',
      'gettingStarted.advocateDesc': 'تبني حلول آمنة وخاصة على زورك؟',
      'gettingStarted.startLearning': 'ابدأ التعلم',
      'gettingStarted.getTechnical': 'كن تقنياً',
      'gettingStarted.getInvolved': 'شارك',
      
      // Footer
      'footer.description': 'بناء مستقبل التكنولوجيا اللامركزية الآمنة والخاصة بأسس مثبتة مشتقة من لايتكوين وخوارزمية kHeavyHash المبتكرة.',
      'footer.community': 'المجتمع',
      'footer.developers': 'المطورون',
      'footer.resources': 'الموارد',
      'footer.documentation': 'التوثيق',
      'footer.apiReference': 'مرجع API',
      'footer.whitepaper': 'الورقة البيضاء',
      'footer.roadmap': 'خارطة الطريق',
      'footer.support': 'الدعم',
      'footer.privacyPolicy': 'سياسة الخصوصية',
      'footer.terms': 'شروط الخدمة',
      'footer.cookies': 'سياسة الكوكيز',
      'footer.copyright': '© 2025 شبكة زورك. جميع الحقوق محفوظة.',
      'footer.pathfinders': 'برنامج الرواد',
      
      // Language Selector
      'language.select': 'اختر اللغة',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    hi: {
      // Header
      'nav.community': 'समुदाय',
      'nav.getStarted': 'शुरू करें',
      'nav.contribute': 'योगदान',
      'nav.zorkcoin': 'जॉर्कऑइन',
      'nav.pathfinders': 'पथप्रदर्शक',
      'nav.joinCommunity': 'शामिल हों',
      
      // Hero
      'hero.welcome': 'स्वागत है',
      'hero.zorkNetwork': 'जॉर्क नेटवर्क में',
      'hero.description': 'एक क्रांतिकारी प्रूफ-ऑफ-वर्क ब्लॉकचेन जो नवाचार kHeavyHash एल्गोरिदम द्वारा संचालित है, सिद्ध लाइटकॉइन तकनीक से प्राप्त। हमारे विविध समुदाय में शामिल हों जो निर्माताओं, रचनाकारों और दूरदर्शियों का है जो सुरक्षित, निजी, विकेंद्रीकृत तकनीक के भविष्य को आकार दे रहे हैं।',
      'hero.getStarted': 'शुरू करें',
      'hero.learnZorkcoin': 'जॉर्कऑइन के बारे में जानें',
      'hero.provenTech': 'सिद्ध तकनीक',
      'hero.provenTechDesc': 'लाइटकॉइन स्रोत कोड से प्राप्त जिसमें दशकों की युद्ध-परीक्षित सुरक्षा है',
      'hero.enhancedPrivacy': 'बेहतर गोपनीयता',
      'hero.enhancedPrivacyDesc': 'बेहतर लेनदेन गोपनीयता के लिए MWEB (MimbleWimble Extension Block) की सुविधा',
      'hero.inclusiveCommunity': 'समावेशी समुदाय',
      'hero.inclusiveCommunityDesc': 'डेवलपर्स, कलाकारों, मार्केटर्स और ब्लॉकचेन नवागतों का स्वागत',
      'hero.kHeavyHash': 'kHeavyHash एल्गोरिदम',
      'hero.kHeavyHashDesc': 'नवाचार खनन एल्गोरिदम जो निष्पक्ष वितरण और ऊर्जा दक्षता सुनिश्चित करता है',
      'hero.devNotice': 'यह साइट, जॉर्क नेटवर्क की बाकी सब चीजों की तरह, अभी भी भारी विकास में है - अभी तक सब कुछ काम नहीं कर रहा है।',
      
      // Community Roles
      'community.title': 'में अपना स्थान खोजें',
      'community.subtitle': 'समुदाय',
      'community.description': 'चाहे आप एक अनुभवी ब्लॉकचेन डेवलपर हों या Web3 में बिल्कुल नए हों, सिद्ध, सुरक्षित तकनीक पर निर्मित जॉर्क नेटवर्क इकोसिस्टम में योगदान देने का एक सार्थक तरीका है।',
      'community.developers': 'डेवलपर्स और प्रोग्रामर',
      'community.developersDesc': 'हमारे लाइटकॉइन-विकसित आधार पर स्मार्ट कॉन्ट्रैक्ट्स, dApps और कोर प्रोटोकॉल सुधार बनाएं',
      'community.artists': 'कलाकार और रचनाकार',
      'community.artistsDesc': 'NFTs डिजाइन करें, सामग्री बनाएं, और हमारे सुरक्षित इकोसिस्टम की दृश्य पहचान बनाएं',
      'community.marketers': 'मार्केटर्स और प्रभावशाली',
      'community.marketersDesc': 'हमारे गोपनीयता-केंद्रित ब्लॉकचेन के बारे में जागरूकता फैलाएं और हमारे समुदाय की पहुंच बढ़ाएं',
      'community.business': 'व्यापारिक डेवलपर्स',
      'community.businessDesc': 'साझेदारी बनाएं, अवसरों की पहचान करें, और जॉर्कऑइन को अपनाने को बढ़ावा दें',
      'community.leaders': 'समुदायिक नेता',
      'community.leadersDesc': 'चर्चाओं का संचालन करें, कार्यक्रम आयोजित करें, और हमारी सिद्ध तकनीक में नवागतों का स्वागत करें',
      'community.enthusiasts': 'Web3 उत्साही',
      'community.enthusiastsDesc': 'सुविधाओं का परीक्षण करें, प्रतिक्रिया प्रदान करें, और नए उपयोगकर्ताओं को हमारे सुरक्षित नेटवर्क में शामिल होने में मदद करें',
      
      // Getting Started
      'gettingStarted.title': 'अपना चुनें',
      'gettingStarted.subtitle': 'यात्रा',
      'gettingStarted.description': 'विभिन्न अनुभव स्तरों और रुचियों के लिए डिजाइन किए गए कई पथ। उस एक को चुनें जो सबसे अच्छा मेल खाता है जहां आप हैं और हमारे सुरक्षित, सिद्ध मंच पर आप कहां जाना चाहते हैं।',
      'gettingStarted.beginner': 'पूर्ण शुरुआती',
      'gettingStarted.beginnerDesc': 'ब्लॉकचेन और क्रिप्टो में नए हैं? यहां शुरू करें!',
      'gettingStarted.technical': 'तकनीकी उपयोगकर्ता',
      'gettingStarted.technicalDesc': 'हमारी सिद्ध तकनीक में गोता लगाने के लिए तैयार हैं?',
      'gettingStarted.contributor': 'समुदायिक योगदानकर्ता',
      'gettingStarted.contributorDesc': 'हमारे सुरक्षित इकोसिस्टम को बढ़ाने में मदद करना चाहते हैं?',
      'gettingStarted.advocate': 'गोपनीयता समर्थक',
      'gettingStarted.advocateDesc': 'जॉर्क पर सुरक्षित, निजी समाधान बना रहे हैं?',
      'gettingStarted.startLearning': 'सीखना शुरू करें',
      'gettingStarted.getTechnical': 'तकनीकी बनें',
      'gettingStarted.getInvolved': 'शामिल हों',
      
      // Footer
      'footer.description': 'सिद्ध लाइटकॉइन-व्युत्पन्न नींव और नवाचार kHeavyHash एल्गोरिदम के साथ सुरक्षित, निजी विकेंद्रीकृत तकनीक का भविष्य बना रहे हैं।',
      'footer.community': 'समुदाय',
      'footer.developers': 'डेवलपर्स',
      'footer.resources': 'संसाधन',
      'footer.documentation': 'दस्तावेज़ीकरण',
      'footer.apiReference': 'API संदर्भ',
      'footer.whitepaper': 'श्वेत पत्र',
      'footer.roadmap': 'रोडमैप',
      'footer.support': 'सहायता',
      'footer.privacyPolicy': 'गोपनीयता नीति',
      'footer.terms': 'सेवा की शर्तें',
      'footer.cookies': 'कुकी नीति',
      'footer.copyright': '© 2025 जॉर्क नेटवर्क। सभी अधिकार सुरक्षित।',
      'footer.pathfinders': 'पथप्रदर्शक कार्यक्रम',
      
      // Language Selector
      'language.select': 'भाषा चुनें',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    ms: {
      // Header
      'nav.community': 'Komuniti',
      'nav.getStarted': 'Mula',
      'nav.contribute': 'Sumbang',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Perintis',
      'nav.joinCommunity': 'Sertai',
      
      // Hero
      'hero.welcome': 'Selamat datang ke',
      'hero.zorkNetwork': 'Rangkaian Zork',
      'hero.description': 'Blockchain bukti kerja yang revolusioner dikuasakan oleh algoritma kHeavyHash yang inovatif, berasal dari teknologi Litecoin yang terbukti. Sertai komuniti pelbagai pembina, pencipta, dan visioner kami yang membentuk masa depan teknologi ternyahpusat yang selamat dan peribadi.',
      'hero.getStarted': 'Mula',
      'hero.learnZorkcoin': 'Pelajari Zorkcoin',
      'hero.provenTech': 'Teknologi Terbukti',
      'hero.provenTechDesc': 'Bercabang dari kod sumber Litecoin dengan dekad keselamatan yang diuji pertempuran',
      'hero.enhancedPrivacy': 'Privasi Dipertingkat',
      'hero.enhancedPrivacyDesc': 'Menampilkan MWEB (MimbleWimble Extension Block) untuk privasi transaksi yang dipertingkat',
      'hero.inclusiveCommunity': 'Komuniti Inklusif',
      'hero.inclusiveCommunityDesc': 'Mengalu-alukan pembangun, artis, pemasar, dan pendatang baru blockchain',
      'hero.kHeavyHash': 'Algoritma kHeavyHash',
      'hero.kHeavyHashDesc': 'Algoritma perlombongan inovatif memastikan pengedaran adil dan kecekapan tenaga',
      'hero.devNotice': 'Laman web ini, seperti segala-galanya untuk Rangkaian Zork, masih dalam pembangunan rapi - tidak semua berfungsi lagi.',
      
      // Community Roles
      'community.title': 'Cari tempat anda dalam',
      'community.subtitle': 'Komuniti',
      'community.description': 'Sama ada anda pembangun blockchain berpengalaman atau benar-benar baru kepada Web3, terdapat cara bermakna untuk anda menyumbang kepada ekosistem Rangkaian Zork yang dibina atas teknologi terbukti dan selamat.',
      'community.developers': 'Pembangun & Pengaturcara',
      'community.developersDesc': 'Bina kontrak pintar, dApps, dan penambahbaikan protokol teras pada asas evolusi Litecoin kami',
      'community.artists': 'Artis & Pencipta',
      'community.artistsDesc': 'Reka bentuk NFT, cipta kandungan, dan bina identiti visual ekosistem selamat kami',
      'community.marketers': 'Pemasar & Influencer',
      'community.marketersDesc': 'Sebarkan kesedaran tentang blockchain fokus privasi kami dan kembangkan jangkauan komuniti kami',
      'community.business': 'Pembangun Perniagaan',
      'community.businessDesc': 'Bentuk perkongsian, kenal pasti peluang, dan dorong penggunaan Zorkcoin',
      'community.leaders': 'Pemimpin Komuniti',
      'community.leadersDesc': 'Moderasi perbincangan, anjur acara, dan alu-alukan pendatang baru kepada teknologi terbukti kami',
      'community.enthusiasts': 'Peminat Web3',
      'community.enthusiastsDesc': 'Uji ciri, berikan maklum balas, dan bantu pengguna baru menyertai rangkaian selamat kami',
      
      // Getting Started
      'gettingStarted.title': 'Pilih',
      'gettingStarted.subtitle': 'Perjalanan anda',
      'gettingStarted.description': 'Pelbagai laluan direka untuk tahap pengalaman dan minat yang berbeza. Pilih yang paling sesuai dengan tempat anda berada dan ke mana anda mahu pergi pada platform selamat dan terbukti kami.',
      'gettingStarted.beginner': 'Pemula Lengkap',
      'gettingStarted.beginnerDesc': 'Baru kepada blockchain dan kripto? Mulakan di sini!',
      'gettingStarted.technical': 'Pengguna Teknikal',
      'gettingStarted.technicalDesc': 'Bersedia untuk menyelami teknologi terbukti kami?',
      'gettingStarted.contributor': 'Penyumbang Komuniti',
      'gettingStarted.contributorDesc': 'Mahu membantu mengembangkan ekosistem selamat kami?',
      'gettingStarted.advocate': 'Penyokong Privasi',
      'gettingStarted.advocateDesc': 'Membina penyelesaian selamat dan peribadi di Zork?',
      'gettingStarted.startLearning': 'Mula Belajar',
      'gettingStarted.getTechnical': 'Jadi Teknikal',
      'gettingStarted.getInvolved': 'Libatkan Diri',
      
      // Footer
      'footer.description': 'Membina masa depan teknologi ternyahpusat yang selamat dan peribadi dengan asas terbukti yang berasal dari Litecoin dan algoritma kHeavyHash yang inovatif.',
      'footer.community': 'Komuniti',
      'footer.developers': 'Pembangun',
      'footer.resources': 'Sumber',
      'footer.documentation': 'Dokumentasi',
      'footer.apiReference': 'Rujukan API',
      'footer.whitepaper': 'Kertas Putih',
      'footer.roadmap': 'Peta Jalan',
      'footer.support': 'Sokongan',
      'footer.privacyPolicy': 'Dasar Privasi',
      'footer.terms': 'Terma Perkhidmatan',
      'footer.cookies': 'Dasar Kuki',
      'footer.copyright': '© 2025 Rangkaian Zork. Semua hak terpelihara.',
      'footer.pathfinders': 'Program Perintis',
      
      // Language Selector
      'language.select': 'Pilih bahasa',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    ta: {
      // Header
      'nav.community': 'சமुதாயம்',
      'nav.getStarted': 'தொடங்கவும்',
      'nav.contribute': 'பங்களிக்கவும்',
      'nav.zorkcoin': 'ஜார்க்கோயின்',
      'nav.pathfinders': 'பாதை காட்டிகள்',
      'nav.joinCommunity': 'சேரவும்',
      
      // Hero
      'hero.welcome': 'வரவேற்கிறோம்',
      'hero.zorkNetwork': 'ஜார்க் நெட்வொர்க்கிற்கு',
      'hero.description': 'புதுமையான kHeavyHash அல்காரிதம் மூலம் இயக்கப்படும் ஒரு புரட்சிகர வேலை-சான்று பிளாக்செயின், நிரூபிக்கப்பட்ட லைட்கோயின் தொழில்நுட்பத்திலிருந்து பெறப்பட்டது. பாதுகாப்பான, தனிப்பட்ட, பரவலாக்கப்பட்ட தொழில்நுட்பத்தின் எதிர்காலத்தை வடிவமைக்கும் எங்கள் பல்வேறு கட்டுனர்கள், படைப்பாளிகள் மற்றும் தொலைநோக்காளர்களின் சமூகத்தில் சேருங்கள்.',
      'hero.getStarted': 'தொடங்கவும்',
      'hero.learnZorkcoin': 'ஜார்க்கோயின் பற்றி அறிக',
      'hero.provenTech': 'நிரூபிக்கப்பட்ட தொழில்நுட்பம்',
      'hero.provenTechDesc': 'பல தசாப்தங்களாக போர்-சோதிக்கப்பட்ட பாதுகாப்புடன் லைட்கோயின் மூல குறியீட்டிலிருந்து கிளைத்தது',
      'hero.enhancedPrivacy': 'மேம்படுத்தப்பட்ட தனியுரிமை',
      'hero.enhancedPrivacyDesc': 'மேம்படுத்தப்பட்ட பரிவர்த்தனை தனியுரிமைக்காக MWEB (MimbleWimble Extension Block) அம்சங்கள்',
      'hero.inclusiveCommunity': 'உள்ளடக்கிய சமுதாயம்',
      'hero.inclusiveCommunityDesc': 'டெவலப்பர்கள், கலைஞர்கள், சந்தைப்படுத்துபவர்கள் மற்றும் பிளாக்செயின் புதியவர்களை வரவேற்கிறது',
      'hero.kHeavyHash': 'kHeavyHash அல்காரிதம்',
      'hero.kHeavyHashDesc': 'நியாயமான விநியோகம் மற்றும் ஆற்றல் திறனை உறுதி செய்யும் புதுமையான சுரங்க அல்காரிதம்',
      'hero.devNotice': 'இந்த தளம், ஜார்க் நெட்வொர்க்கிற்கான மற்ற எல்லாவற்றையும் போலவே, இன்னும் கடுமையான வளர்ச்சியில் உள்ளது - எல்லாம் இன்னும் வேலை செய்யவில்லை.',
      
      // Community Roles
      'community.title': 'இல் உங்கள் இடத்தைக் கண்டறியுங்கள்',
      'community.subtitle': 'சமுதாயம்',
      'community.description': 'நீங்கள் அனுபவமிக்க பிளாக்செயின் டெவலப்பராக இருந்தாலும் அல்லது Web3க்கு முற்றிலும் புதியவராக இருந்தாலும், நிரூபிக்கப்பட்ட, பாதுகாப்பான தொழில்நுட்பத்தில் கட்டப்பட்ட ஜார்க் நெட்வொர்க் சூழலமைப்பிற்கு பங்களிக்க உங்களுக்கு ஒரு அர்த்தமுள்ள வழி உள்ளது.',
      'community.developers': 'டெவலப்பர்கள் & புரோகிராமர்கள்',
      'community.developersDesc': 'எங்கள் லைட்கோயின்-பரிணாம அடித்தளத்தில் ஸ்மார்ட் ஒப்பந்தங்கள், dApps மற்றும் முக்கிய நெறிமுறை மேம்பாடுகளை உருவாக்குங்கள்',
      'community.artists': 'கலைஞர்கள் & படைப்பாளிகள்',
      'community.artistsDesc': 'NFTகளை வடிவமைக்கவும், உள்ளடக்கத்தை உருவாக்கவும், எங்கள் பாதுகாப்பான சூழலமைப்பின் காட்சி அடையாளத்தை உருவாக்கவும்',
      'community.marketers': 'சந்தைப்படுத்துபவர்கள் & செல்வாக்காளர்கள்',
      'community.marketersDesc': 'எங்கள் தனியுரிமை-மையமான பிளாக்செயின் பற்றிய விழிப்புணர்வை பரப்புங்கள் மற்றும் எங்கள் சமூக அணுகலை வளர்க்கவும்',
      'community.business': 'வணிக டெவலப்பர்கள்',
      'community.businessDesc': 'கூட்டாண்மைகளை உருவாக்குங்கள், வாய்ப்புகளை அடையாளம் காணுங்கள், மற்றும் ஜார்க்கோயின் ஏற்றுக்கொள்ளலை உந்துங்கள்',
      'community.leaders': 'சமூக தலைவர்கள்',
      'community.leadersDesc': 'விவாதங்களை மதிப்பிடுங்கள், நிகழ்வுகளை ஏற்பாடு செய்யுங்கள், மற்றும் எங்கள் நிரூபிக்கப்பட்ட தொழில்நுட்பத்திற்கு புதியவர்களை வரவேற்கவும்',
      'community.enthusiasts': 'Web3 ஆர்வலர்கள்',
      'community.enthusiastsDesc': 'அம்சங்களை சோதிக்கவும், கருத்துக்களை வழங்கவும், மற்றும் புதிய பயனர்களை எங்கள் பாதுகாப்பான நெட்வொர்க்கில் சேர உதவவும்',
      
      // Getting Started
      'gettingStarted.title': 'உங்கள் தேர்வு செய்யுங்கள்',
      'gettingStarted.subtitle': 'பயணம்',
      'gettingStarted.description': 'பல்வேறு அனுபவ நிலைகள் மற்றும் ஆர்வங்களுக்காக வடிவமைக்கப்பட்ட பல பாதைகள். நீங்கள் எங்கே இருக்கிறீர்கள் மற்றும் எங்கள் பாதுகாப்பான, நிரூபிக்கப்பட்ட தளத்தில் நீங்கள் எங்கே செல்ல விரும்புகிறீர்கள் என்பதற்கு மிகவும் பொருந்தும் ஒன்றைத் தேர்ந்தெடுக்கவும்.',
      'gettingStarted.beginner': 'முழுமையான புதியவர்',
      'gettingStarted.beginnerDesc': 'பிளாக்செயின் மற்றும் கிரிப்டோவிற்கு புதியவரா? இங்கே தொடங்குங்கள்!',
      'gettingStarted.technical': 'தொழில்நுட்ப பயனர்',
      'gettingStarted.technicalDesc': 'எங்கள் நிரூபிக்கப்பட்ட தொழில்நுட்பத்தில் மூழ்கத் தயாரா?',
      'gettingStarted.contributor': 'சமூக பங்களிப்பாளர்',
      'gettingStarted.contributorDesc': 'எங்கள் பாதுகாப்பான சூழலமைப்பை வளர்க்க உதவ விரும்புகிறீர்களா?',
      'gettingStarted.advocate': 'தனியுரிமை வக்கீல்',
      'gettingStarted.advocateDesc': 'ஜார்க்கில் பாதுகாப்பான, தனிப்பட்ட தீர்வுகளை உருவாக்குகிறீர்களா?',
      'gettingStarted.startLearning': 'கற்றல் தொடங்கவும்',
      'gettingStarted.getTechnical': 'தொழில்நுட்பமாக மாறுங்கள்',
      'gettingStarted.getInvolved': 'பங்கேற்கவும்',
      
      // Footer
      'footer.description': 'நிரூபிக்கப்பட்ட லைட்கோயின்-பெறப்பட்ட அடித்தளங்கள் மற்றும் புதுமையான kHeavyHash அல்காரிதம் மூலம் பாதுகாப்பான, தனிப்பட்ட பரவலாக்கப்பட்ட தொழில்நுட்பத்தின் எதிர்காலத்தை உருவாக்குகிறோம்.',
      'footer.community': 'சமுதாயம்',
      'footer.developers': 'டெவலப்பர்கள்',
      'footer.resources': 'வளங்கள்',
      'footer.documentation': 'ஆவணப்படுத்தல்',
      'footer.apiReference': 'API குறிப்பு',
      'footer.whitepaper': 'வெள்ளை காகிதம்',
      'footer.roadmap': 'சாலை வரைபடம்',
      'footer.support': 'ஆதரவு',
      'footer.privacyPolicy': 'தனியுரிமை கொள்கை',
      'footer.terms': 'சேவை விதிமுறைகள்',
      'footer.cookies': 'குக்கீ கொள்கை',
      'footer.copyright': '© 2025 ஜார்க் நெட்வொர்க். அனைத்து உரிமைகளும் பாதுகாக்கப்படுகின்றன.',
      'footer.pathfinders': 'பாதை காட்டிகள் திட்டம்',
      
      // Language Selector
      'language.select': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
    tl: {
      // Header
      'nav.community': 'Komunidad',
      'nav.getStarted': 'Magsimula',
      'nav.contribute': 'Mag-ambag',
      'nav.zorkcoin': 'Zorkcoin',
      'nav.pathfinders': 'Pathfinders',
      'nav.joinCommunity': 'Sumali',
      
      // Hero
      'hero.welcome': 'Maligayang pagdating sa',
      'hero.zorkNetwork': 'Zork Network',
      'hero.description': 'Isang rebolusyonaryong proof-of-work blockchain na pinapagana ng makabagong kHeavyHash algorithm, nagmula sa napatunayang teknolohiya ng Litecoin. Sumali sa aming magkakaibang komunidad ng mga tagabuo, mga manlakabay, at mga taong may malawakang pananaw na naghuhubog sa kinabukasan ng secure, pribado, desentralisadong teknolohiya.',
      'hero.getStarted': 'Magsimula',
      'hero.learnZorkcoin': 'Matuto tungkol sa Zorkcoin',
      'hero.provenTech': 'Napatunayang Teknolohiya',
      'hero.provenTechDesc': 'Nakuha mula sa Litecoin source code na may mga dekadang battle-tested na seguridad',
      'hero.enhancedPrivacy': 'Pinahusay na Privacy',
      'hero.enhancedPrivacyDesc': 'May mga feature ng MWEB (MimbleWimble Extension Block) para sa pinahusay na transaction privacy',
      'hero.inclusiveCommunity': 'Kasama-samang Komunidad',
      'hero.inclusiveCommunityDesc': 'Tumatanggap ng mga developer, artist, marketer, at mga baguhan sa blockchain',
      'hero.kHeavyHash': 'kHeavyHash Algorithm',
      'hero.kHeavyHashDesc': 'Makabagong mining algorithm na nagsisiguro ng makatarungang pamamahagi at energy efficiency',
      'hero.devNotice': 'Ang site na ito, tulad ng lahat ng iba pa para sa Zork Network, ay nasa mabigat na development pa - hindi pa lahat ay gumagana.',
      
      // Community Roles
      'community.title': 'Hanapin ang inyong lugar sa',
      'community.subtitle': 'Komunidad',
      'community.description': 'Maging experienced blockchain developer kayo o baguhan sa Web3, may makabuluhang paraan para kayo mag-contribute sa Zork Network ecosystem na nakatayo sa napatunayang, secure na teknolohiya.',
      'community.developers': 'Mga Developer at Programmer',
      'community.developersDesc': 'Magbuo ng smart contracts, dApps, at core protocol improvements sa aming Litecoin-evolved foundation',
      'community.artists': 'Mga Artist at Creator',
      'community.artistsDesc': 'Mag-design ng mga NFT, lumikha ng content, at bumuo ng visual identity ng aming secure ecosystem',
      'community.marketers': 'Mga Marketer at Influencer',
      'community.marketersDesc': 'Ikalat ang kamalayan sa aming privacy-focused blockchain at palaguin ang reach ng aming komunidad',
      'community.business': 'Mga Business Developer',
      'community.businessDesc': 'Bumuo ng mga partnership, tukuyin ang mga oportunidad, at itulak ang adoption ng Zorkcoin',
      'community.leaders': 'Mga Community Leader',
      'community.leadersDesc': 'Mag-moderate ng mga discussion, mag-organize ng mga event, at tanggapin ang mga newcomer sa aming napatunayang teknolohiya',
      'community.enthusiasts': 'Mga Web3 Enthusiast',
      'community.enthusiastsDesc': 'Subukan ang mga feature, magbigay ng feedback, at tulungang sumali ang mga bagong user sa aming secure network',
      
      // Getting Started
      'gettingStarted.title': 'Piliin ang inyong',
      'gettingStarted.subtitle': 'Paglalakbay',
      'gettingStarted.description': 'Maraming pathway na dinisenyo para sa iba\'t ibang experience level at mga interes. Piliin ang pinaka-tugma sa kung nasaan kayo at kung saan kayo gustong pumunta sa aming secure, napatunayang platform.',
      'gettingStarted.beginner': 'Kumpletong Baguhan',
      'gettingStarted.beginnerDesc': 'Baguhan sa blockchain at crypto? Magsimula dito!',
      'gettingStarted.technical': 'Technical User',
      'gettingStarted.technicalDesc': 'Handa na bang sumisid sa aming napatunayang teknolohiya?',
      'gettingStarted.contributor': 'Community Contributor',
      'gettingStarted.contributorDesc': 'Gusto bang tumulong sa paglaki ng aming secure ecosystem?',
      'gettingStarted.advocate': 'Privacy Advocate',
      'gettingStarted.advocateDesc': 'Gumagawa ng secure, private na mga solusyon sa Zork?',
      'gettingStarted.startLearning': 'Simulang Matuto',
      'gettingStarted.getTechnical': 'Maging Technical',
      'gettingStarted.getInvolved': 'Makisali',
      
      // Footer
      'footer.description': 'Nagtatayo ng kinabukasan ng secure, private na desentralisadong teknolohiya gamit ang napatunayang Litecoin-derived foundations at ang makabagong kHeavyHash algorithm.',
      'footer.community': 'Komunidad',
      'footer.developers': 'Mga Developer',
      'footer.resources': 'Mga Resources',
      'footer.documentation': 'Documentation',
      'footer.apiReference': 'API Reference',
      'footer.whitepaper': 'Whitepaper',
      'footer.roadmap': 'Roadmap',
      'footer.support': 'Support',
      'footer.privacyPolicy': 'Privacy Policy',
      'footer.terms': 'Terms of Service',
      'footer.cookies': 'Cookie Policy',
      'footer.copyright': '© 2025 Zork Network. Lahat ng karapatan ay nakalaan.',
      'footer.pathfinders': 'Pathfinders Program',
      
      // Language Selector
      'language.select': 'Piliin ang wika',
      'language.english': 'English',
      'language.russian': 'Русский',
      'language.chinese': '中文',
      'language.german': 'Deutsch',
      'language.french': 'Français',
      'language.spanish': 'Español',
      'language.portuguese': 'Português',
      'language.arabic': 'العربية',
      'language.hindi': 'हिन्दी',
      'language.malay': 'Bahasa Melayu',
      'language.tamil': 'தமிழ்',
      'language.filipino': 'Filipino',
    },
  };
};
